### ISSUE TITLE
Incorrect permissions

### ISSUE THREAD

**Issue by jakoraptor** [jakoraptor/send2sift#1]
The cortex responder does not have permissions to access <code>/home/thehive/.ssh/id_rsa</code> as the responder runs as the user "cortex" not "thehive". See the following cortex error.

> Traceback (most recent call last):  File "/opt/Cortex-Analyzers/responders/Send2Sift/send2sift.py", line 35, in <module>    SendToSift().run()  File "/opt/Cortex-Analyzers/responders/Send2Sift/send2sift.py", line 25, in run    remote.bulk_upload(local_files)  File "/opt/Cortex-Analyzers/responders/Send2Sift/client.py", line 75, in bulk_upload    self.scp.put(files, remote_path=self.remote_path)  File "/opt/Cortex-Analyzers/responders/Send2Sift/client.py", line 48, in scp    conn = self.connection  File "/opt/Cortex-Analyzers/responders/Send2Sift/client.py", line 39, in connection    timeout=5000,  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 446, in connect    passphrase,  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 677, in _auth    key_filename, pkey_class, passphrase  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 586, in _key_from_filepath    key = klass.from_private_key_file(key_path, password)  File "/usr/local/lib/python3.6/dist-packages/paramiko/pkey.py", line 235, in from_private_key_file    key = cls(filename=filename, password=password)  File "/usr/local/lib/python3.6/dist-packages/paramiko/rsakey.py", line 55, in __init__    self._from_private_key_file(filename, password)  File "/usr/local/lib/python3.6/dist-packages/paramiko/rsakey.py", line 175, in _from_private_key_file    data = self._read_private_key_file("RSA", filename, password)  File "/usr/local/lib/python3.6/dist-packages/paramiko/pkey.py", line 307, in _read_private_key_file    with open(filename, "r") as f:PermissionError: [Errno 13] Permission denied: '/home/thehive/.ssh/id_rsa'

**Comment by jakoraptor** [comment]
this works but requires extra step

> run the following commands to create a cortex user
> as root
> 
> * mkdir /home/cortex/.ssh
* **chown -r cortex:cortex /home/cortex**
> * cp id_rsa file to /home/cortex/.ssh
> * chmod 600 /home/cortex/.ssh/id_rsa
> 
> Try again :)
